### ISSUE TITLE
New org

### ISSUE THREAD

**Issue by remojansen** [FullstackTypeScript/redux-bootstrap#88]
Hi @veeramarni @jokeyrhyme 

I'm re-organizing some of my stuff on Github and I have big plans related with TypeScript. When I created this organization the plan was to create tools to help Redux developers but I want to increase the scope and help TypeScript developers in general. 

So I have created a new org https://github.com/FullstackTypeScript and I have plans to transfer the repositories from this org to the new org.

I will invite you to join the new org :smile:

**Comment by veeramarni** [comment]
@remojansen I'm working on creating a lerna package system to incrementally add packages to avoid being too opinionated with packages and provide a various way to implement react redux best practices. Also, we can inject reducer's to develop a highly scalable app. 
Created something [here](https://github.com/cdmbase/react-frontend-server-stack)
This is highly experimental now, but once it comes to a stable point, I want to push it here. 

I will also look forward to new FullStackTypescript plan.

**Comment by remojansen** [comment]
@veeramarni that soudns great for me the Idea is to use FullStackTypescript as a place for people to share TypeScript projects that will help other TS developers :)

**Comment by remojansen** [comment]
Welcome to the new org 🎉
