### ISSUE TITLE
[enhancement] It should be possible to configure redux-devtools-extension.

### ISSUE THREAD

**Issue by lukaswelinder** [FullstackTypeScript/redux-bootstrap#89]
## Expected Behavior
Redux devtools should be configurable using the bootstrap options.

## Current Behavior
Currently the redux-devtools options are hard-coded to serialize w/ Immutable.js.

## Possible Solution
Allow `devToolsOptions` property on `bootstrap` options that (if defined) is used instead of the default. This would require extending the `interface DevToolsOptions` due to its current (limited) coverage.

## Context
Not allowing configuration of the serialization behavior of devtools has been problematic for us. It means that we cannot pass events or dom nodes with actions. The biggest problem is that the resulting error is incredibly difficult to trace back to redux-devtools serialization.

## Your Environment
* Version used: 1.2.0

**Comment by remojansen** [comment]
The PR has been merged
